# Generated by Django 5.1.3 on 2024-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cancion_test_alter_cancion_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='cover',
            field=models.FileField(default='temp', upload_to='./archivosBd/imagenes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='canciones',
            field=models.ManyToManyField(blank=True, to='app.cancion'),
        ),
    ]
