# Generated by Django 5.1.3 on 2024-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cancion_cover_playlist_canciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='archivo',
            field=models.FileField(upload_to='./archibosBd/imagenes'),
        ),
    ]
