# Generated by Django 5.1.3 on 2024-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cancion_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='archivo1',
            field=models.URLField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancion',
            name='cover1',
            field=models.URLField(default='temp2'),
            preserve_default=False,
        ),
    ]
