# Generated by Django 5.1.3 on 2024-11-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cancion_archivo1_cancion_cover1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='cancion',
            name='cover',
        ),
    ]
