# Generated by Django 5.1.3 on 2024-11-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_cancion_archivo_remove_cancion_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='archivo',
            field=models.URLField(default='t'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancion',
            name='cover',
            field=models.URLField(default='t'),
            preserve_default=False,
        ),
    ]
