# Generated by Django 5.1.4 on 2024-12-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_playlist_autor_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='archivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='cover',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.TextField(),
        ),
    ]
