# Generated by Django 5.1.4 on 2024-12-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cancion_archivo_alter_cancion_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='archivo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='cover',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.CharField(max_length=200),
        ),
    ]
